// <auto-generated />
using System;
using FafCarsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FafCarsApi.Migrations
{
    [DbContext(typeof(FafCarsDbContext))]
    [Migration("20240516210411_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FafCarsApi.Models.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand");

                    b.Property<int?>("Clearance")
                        .HasColumnType("integer")
                        .HasColumnName("clearance");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EngineType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("engine_type");

                    b.Property<double?>("EngineVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("engine_volume");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer")
                        .HasColumnName("horsepower");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("PreviewFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("preview_file_name");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("WheelSize")
                        .HasColumnType("integer")
                        .HasColumnName("wheel_size");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("listings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07cd8a32-44c6-4f29-bfd1-f56f933842a7"),
                            BrandName = "BMW",
                            Clearance = 210,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2024, 5, 17, 0, 4, 10, 613, DateTimeKind.Local).AddTicks(614),
                            EngineType = "Petrol",
                            EngineVolume = 3.0,
                            Horsepower = 300,
                            Mileage = 15000,
                            ModelName = "X5",
                            Price = 35000.0,
                            PublisherId = new Guid("e4dc0371-2331-4689-9dff-3dab740f59c9"),
                            Type = "SUV",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("5fc0b7d3-c2ef-4701-b6bd-bd1fecc77d1b"),
                            BrandName = "Toyota",
                            Clearance = 170,
                            Color = "#007A5E",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2024, 5, 17, 0, 4, 10, 613, DateTimeKind.Local).AddTicks(1339),
                            EngineType = "Hybrid",
                            EngineVolume = 2.5,
                            Horsepower = 208,
                            Mileage = 10000,
                            ModelName = "Camry",
                            Price = 25000.0,
                            PublisherId = new Guid("e4dc0371-2331-4689-9dff-3dab740f59c9"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("6a0def42-38de-4568-b0f0-192b1413c611"),
                            BrandName = "Ford",
                            Clearance = 230,
                            Color = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 3.5,
                            Horsepower = 375,
                            Mileage = 25000,
                            ModelName = "F-150",
                            Price = 30000.0,
                            PublisherId = new Guid("e4dc0371-2331-4689-9dff-3dab740f59c9"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 17,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("fc5a1e8f-f099-4e13-be28-4a25e3a07794"),
                            BrandName = "Honda",
                            Clearance = 160,
                            Color = "#002366",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 1.8,
                            Horsepower = 174,
                            Mileage = 20000,
                            ModelName = "Civic",
                            Price = 18000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 16,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("67498b2a-1eac-4972-bd2f-f78f32d3af11"),
                            BrandName = "Mercedes-Benz",
                            Clearance = 180,
                            Color = "#1C1C1C",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Diesel",
                            EngineVolume = 2.0,
                            Horsepower = 240,
                            Mileage = 18000,
                            ModelName = "E-Class",
                            Price = 40000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("49f0fa8c-e980-4000-b77f-49c97a553086"),
                            BrandName = "Chevrolet",
                            Clearance = 250,
                            Color = "#800000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.2999999999999998,
                            Horsepower = 355,
                            Mileage = 12000,
                            ModelName = "Silverado",
                            Price = 38000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("d055aa20-036d-4a05-a6cf-644d421c5b19"),
                            BrandName = "Chevrolet",
                            Clearance = 250,
                            Color = "#800000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.2999999999999998,
                            Horsepower = 355,
                            Mileage = 12000,
                            ModelName = "Silverado",
                            Price = 38000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("36575e04-d26f-4d8d-b316-aa52e4426a70"),
                            BrandName = "Ford",
                            Clearance = 230,
                            Color = "#0000FF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.0,
                            Horsepower = 375,
                            Mileage = 10000,
                            ModelName = "F-150",
                            Price = 42000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("1d205787-f87d-4ea7-821c-7f91d90060d8"),
                            BrandName = "Toyota",
                            Clearance = 240,
                            Color = "#006400",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 3.5,
                            Horsepower = 278,
                            Mileage = 15000,
                            ModelName = "Tacoma",
                            Price = 34000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 17,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("3c34c4cf-d60d-4a52-a7fa-92e9fd28a232"),
                            BrandName = "Honda",
                            Clearance = 150,
                            Color = "#FFA500",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 2.0,
                            Horsepower = 174,
                            Mileage = 20000,
                            ModelName = "Civic",
                            Price = 22000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 16,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("0a232e44-7269-4512-a8b9-0523b6a50b66"),
                            BrandName = "BMW",
                            Clearance = 140,
                            Color = "#000000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 2.0,
                            Horsepower = 255,
                            Mileage = 18000,
                            ModelName = "3 Series",
                            Price = 35000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("71dde5bc-462c-4e49-91b0-1a5575258067"),
                            BrandName = "Tesla",
                            Clearance = 160,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Electric",
                            EngineVolume = 0.0,
                            Horsepower = 450,
                            Mileage = 5000,
                            ModelName = "Model 3",
                            Price = 50000.0,
                            PublisherId = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 19,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4dc0371-2331-4689-9dff-3dab740f59c9"),
                            CreatedAt = new DateTime(2024, 5, 17, 0, 4, 9, 986, DateTimeKind.Local).AddTicks(5501),
                            Email = "warek@gmail.com",
                            Password = "$2a$13$fTX/OXOAybxCuKnoSxcD5eGcW8aD24sRJpEHO2xR6qqCaSIMOBdaq",
                            Roles = new[] { 1 },
                            UpdatedAt = new DateTime(2024, 5, 17, 0, 4, 9, 989, DateTimeKind.Local).AddTicks(4590),
                            Username = "warek"
                        },
                        new
                        {
                            Id = new Guid("fa37b5f1-9239-435b-ad92-d9a5f689f4ee"),
                            CreatedAt = new DateTime(2024, 5, 17, 0, 4, 10, 610, DateTimeKind.Local).AddTicks(5179),
                            Email = "denis@gmail.com",
                            Password = "$2a$13$VomVLnp2vyMqjeBco3I5We/wJq5m0F4Xu8JqiCFMeDBH6J1kZIOBG",
                            Roles = new[] { 0, 3 },
                            UpdatedAt = new DateTime(2024, 5, 17, 0, 4, 10, 610, DateTimeKind.Local).AddTicks(5277),
                            Username = "denis"
                        });
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.Listing", b =>
                {
                    b.HasOne("FafCarsApi.Models.Entities.User", "Publisher")
                        .WithMany("Listings")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.User", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
