// <auto-generated />
using System;
using FafCarsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FafCarsApi.Migrations
{
    [DbContext(typeof(FafCarsDbContext))]
    [Migration("20240511130825_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FafCarsApi.Models.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("brand");

                    b.Property<int?>("Clearance")
                        .HasColumnType("integer")
                        .HasColumnName("clearance");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EngineType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("engine_type");

                    b.Property<double?>("EngineVolume")
                        .HasColumnType("double precision")
                        .HasColumnName("engine_volume");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer")
                        .HasColumnName("horsepower");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("preview_url");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(0) WITHOUT TIME ZONE")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("WheelSize")
                        .HasColumnType("integer")
                        .HasColumnName("wheel_size");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("listings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d45f346-1f5a-4bd0-b023-ea29fbacec69"),
                            BrandName = "BMW",
                            Clearance = 210,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2024, 5, 11, 16, 8, 25, 152, DateTimeKind.Local).AddTicks(6885),
                            EngineType = "Petrol",
                            EngineVolume = 3.0,
                            Horsepower = 300,
                            Mileage = 15000,
                            ModelName = "X5",
                            Price = 35000.0,
                            PublisherId = new Guid("34de19e0-3217-4207-b050-3e9f1eb42644"),
                            Type = "SUV",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("3a1fa808-da94-4cc3-862b-5796675da0d3"),
                            BrandName = "Toyota",
                            Clearance = 170,
                            Color = "#007A5E",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(2024, 5, 11, 16, 8, 25, 154, DateTimeKind.Local).AddTicks(2031),
                            EngineType = "Hybrid",
                            EngineVolume = 2.5,
                            Horsepower = 208,
                            Mileage = 10000,
                            ModelName = "Camry",
                            Price = 25000.0,
                            PublisherId = new Guid("34de19e0-3217-4207-b050-3e9f1eb42644"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("79e66eeb-0dc6-4154-8367-d29c20c7e97d"),
                            BrandName = "Ford",
                            Clearance = 230,
                            Color = "#FF0000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 3.5,
                            Horsepower = 375,
                            Mileage = 25000,
                            ModelName = "F-150",
                            PreviewUrl = "https://localhost:44391/api/file/car-1.jpg",
                            Price = 30000.0,
                            PublisherId = new Guid("34de19e0-3217-4207-b050-3e9f1eb42644"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 17,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("e9948aa9-29bf-4399-85be-dc8216e1d399"),
                            BrandName = "Honda",
                            Clearance = 160,
                            Color = "#002366",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 1.8,
                            Horsepower = 174,
                            Mileage = 20000,
                            ModelName = "Civic",
                            Price = 18000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 16,
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("dd797484-1ca2-4a2b-9a27-2641076621de"),
                            BrandName = "Mercedes-Benz",
                            Clearance = 180,
                            Color = "#1C1C1C",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Diesel",
                            EngineVolume = 2.0,
                            Horsepower = 240,
                            Mileage = 18000,
                            ModelName = "E-Class",
                            Price = 40000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("00180b5a-ffdd-4d93-8ef9-ccb79c668b88"),
                            BrandName = "Chevrolet",
                            Clearance = 250,
                            Color = "#800000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.2999999999999998,
                            Horsepower = 355,
                            Mileage = 12000,
                            ModelName = "Silverado",
                            Price = 38000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("40f7b072-806e-4119-8645-365808a47769"),
                            BrandName = "Chevrolet",
                            Clearance = 250,
                            Color = "#800000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.2999999999999998,
                            Horsepower = 355,
                            Mileage = 12000,
                            ModelName = "Silverado",
                            Price = 38000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 20,
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("11268a9a-ef7e-4e26-abb9-0dc01a24cd9a"),
                            BrandName = "Ford",
                            Clearance = 230,
                            Color = "#0000FF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 5.0,
                            Horsepower = 375,
                            Mileage = 10000,
                            ModelName = "F-150",
                            Price = 42000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("08dc46a0-8f69-4376-a822-790eb27855eb"),
                            BrandName = "Toyota",
                            Clearance = 240,
                            Color = "#006400",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 3.5,
                            Horsepower = 278,
                            Mileage = 15000,
                            ModelName = "Tacoma",
                            Price = 34000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Truck",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 17,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("2c73b60c-8a12-41c8-bad3-e44522d73e1b"),
                            BrandName = "Honda",
                            Clearance = 150,
                            Color = "#FFA500",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 2.0,
                            Horsepower = 174,
                            Mileage = 20000,
                            ModelName = "Civic",
                            Price = 22000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 16,
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("a5f48973-77f1-4217-981d-fd437a5017ae"),
                            BrandName = "BMW",
                            Clearance = 140,
                            Color = "#000000",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Gasoline",
                            EngineVolume = 2.0,
                            Horsepower = 255,
                            Mileage = 18000,
                            ModelName = "3 Series",
                            Price = 35000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 18,
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("44749168-6e3a-4128-a611-60f25800a83e"),
                            BrandName = "Tesla",
                            Clearance = 160,
                            Color = "#FFFFFF",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EngineType = "Electric",
                            EngineVolume = 0.0,
                            Horsepower = 450,
                            Mileage = 5000,
                            ModelName = "Model 3",
                            Price = 50000.0,
                            PublisherId = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Type = "Sedan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WheelSize = 19,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("password");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34de19e0-3217-4207-b050-3e9f1eb42644"),
                            Email = "warek@gmail.com",
                            Password = "$2a$13$s7vtn2zvuVyZDCth3tz7leduUraPXr11s83ZsA2hD2Zhx4P5m.xCO",
                            Roles = new[] { 1 },
                            Username = "warek"
                        },
                        new
                        {
                            Id = new Guid("5a3680a5-0f06-433e-b6a6-e7509bafca7a"),
                            Email = "denis@gmail.com",
                            Password = "$2a$13$J1YT7U7aGV1CvtwB.ceGmuUnv2okuMHeuBfaHx7fdXP6Nio4T2KOS",
                            Roles = new[] { 0, 3 },
                            Username = "denis"
                        });
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.Listing", b =>
                {
                    b.HasOne("FafCarsApi.Models.Entities.User", "Publisher")
                        .WithMany("Listings")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FafCarsApi.Models.Entities.User", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
