// <auto-generated />
using System;
using System.Collections.Generic;
using FafCarsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FafCarsApi.Migrations
{
    [DbContext(typeof(FafCarsDbContext))]
    partial class FafCarsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FafCarsApi.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("UUID_GENERATE_V4()");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Clearance")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE");

                    b.Property<string>("EngineType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double?>("EngineVolume")
                        .HasColumnType("double precision");

                    b.Property<int?>("Horsepower")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Preview")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("WheelSize")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PublisherId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("FafCarsApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("UUID_GENERATE_V4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(1) WITHOUT TIME ZONE")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdb7604f-ddda-439c-8139-bffda01a8580"),
                            CreatedAt = new DateTime(2024, 6, 13, 22, 15, 10, 780, DateTimeKind.Local).AddTicks(8263),
                            Email = "admin@gmail.com",
                            Password = "$2a$13$1jNFjOjBWBfLptFL.YsttecglR2sMK5.iKpyV8gefJwQKncv6vNrW",
                            PhoneNumber = "+37378000111",
                            Roles = new[] { 0, 1 },
                            UpdatedAt = new DateTime(2024, 6, 13, 22, 15, 10, 791, DateTimeKind.Local).AddTicks(1062),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("5df812c8-d8be-4a9f-92f3-0cc5b3b78a1d"),
                            CreatedAt = new DateTime(2024, 6, 13, 22, 15, 11, 257, DateTimeKind.Local).AddTicks(6514),
                            Email = "user@gmail.com",
                            Password = "$2a$13$9vlKSuKKmE70FLa/5ujDA.U1l.QJ2N3sEPQKzpRHlvs31UWg4nSxa",
                            PhoneNumber = "+37378111222",
                            Roles = new[] { 0 },
                            UpdatedAt = new DateTime(2024, 6, 13, 22, 15, 11, 257, DateTimeKind.Local).AddTicks(6611),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("ListingUser", b =>
                {
                    b.Property<Guid>("FavoritesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersFavoritesId")
                        .HasColumnType("uuid");

                    b.HasKey("FavoritesId", "UsersFavoritesId");

                    b.HasIndex("UsersFavoritesId");

                    b.ToTable("ListingUser");
                });

            modelBuilder.Entity("FafCarsApi.Models.Listing", b =>
                {
                    b.HasOne("FafCarsApi.Models.User", "Publisher")
                        .WithMany("Listings")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ListingUser", b =>
                {
                    b.HasOne("FafCarsApi.Models.Listing", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FafCarsApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersFavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FafCarsApi.Models.User", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
