INSERT INTO "Cities" ("CountryCode", "Name")
VALUES ('DE', 'Berlin'),
       ('DE', 'Hamburg'),
       ('DE', 'Munich'),
       ('DE', 'Cologne'),
       ('DE', 'Frankfurt'),
       ('DE', 'Stuttgart'),
       ('DE', 'Dusseldorf'),
       ('DE', 'Dortmund'),
       ('DE', 'Essen'),
       ('DE', 'Bremen'),
       ('DE', 'Dresden'),
       ('DE', 'Leipzig'),
       ('DE', 'Hanover'),
       ('DE', 'Nuremberg'),
       ('US', 'New York'),
       ('US', 'Los Angeles'),
       ('US', 'Chicago'),
       ('US', 'Houston'),
       ('US', 'Phoenix'),
       ('US', 'Philadelphia'),
       ('US', 'San Antonio'),
       ('US', 'San Diego'),
       ('US', 'Dallas'),
       ('US', 'San Jose'),
       ('GB', 'London'),
       ('GB', 'Manchester'),
       ('GB', 'Birmingham'),
       ('GB', 'Liverpool'),
       ('GB', 'Leeds'),
       ('GB', 'Sheffield'),
       ('GB', 'Bristol'),
       ('GB', 'Glasgow'),
       ('GB', 'Edinburgh'),
       ('JP', 'Tokyo'),
       ('JP', 'Yokohama'),
       ('JP', 'Osaka'),
       ('JP', 'Nagoya'),
       ('JP', 'Sapporo'),
       ('JP', 'Fukuoka'),
       ('JP', 'Kobe'),
       ('JP', 'Kyoto'),
       ('JP', 'Kawasaki'),
       ('CN', 'Shanghai'),
       ('CN', 'Beijing'),
       ('CN', 'Guangzhou'),
       ('CN', 'Shenzhen'),
       ('CN', 'Chongqing'),
       ('CN', 'Tianjin'),
       ('CN', 'Wuhan'),
       ('CN', 'Dongguan'),
       ('CN', 'Chengdu'),
       ('CN', 'Nanjing');
